<?php

echo "VAI CORINTHIANS";
echo "VAI CORINTHIANS";
echo "VAI CORINTHIANS";
echo "VAI CORINTHIANS";
echo "VAI CORINTHIANS";


echo "PALMEIRAS SEM MUNDIAL";
echo "PALMEIRAS SEM MUNDIAL";

echo "PALMEIRAS SEM MUNDIAL";
echo "PALMEIRAS SEM MUNDIAL";
?>
